[workspace]
members = [
    "gwm-core",
    "gwm-kbd",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'

# [replace]
# "xkb:0.1.2" = { git = "https://github.com/ibabushkin/rust-xkb" }
