#!/bin/sh
Xephyr -ac -br -noreset -screen 800x600 :1.0 &
sleep 1
# TODO: run with proper path 
if [ "$1" == "-k" ]; then
  DISPLAY=:1.0 "./target/debug/gabelstaplergrab"
else
  DISPLAY=:1.0 "./target/debug/gabelstaplerwm"
fi
