modkey = "mod1"

active_modes = [
  "normal", # first mode listed is default
  "swap",
  "move",
  "ignore"
]

[modes.normal]
enter_binding = "$modkey+n"
enter_binding_quick_leave = "$modkey+M n"
enter_command = "echo 'n'"
leave_command = "echo '!n'"

[modes.normal.bindings]
"$modkey+x $modkey+h" = "echo xh"
"$modkey+x $modkey+j" = "echo xj"
"$modkey+x $modkey+k" = "echo xk"
"$modkey+x $modkey+l" = "echo xl"
"$modkey+h" = "echo h"
"$modkey+j" = "echo j"
"$modkey+k" = "echo k"
"$modkey+l" = "echo l"
"$modkey+shift+h" = "echo h"
"$modkey+shift+j" = "echo j"
"$modkey+shift+k" = "echo k"
"$modkey+shift+l" = "echo l"

[modes.swap]
enter_binding = "$modkey+s"
enter_binding_quick_leave = "$modkey+M s"
bindings = {}

[modes.move]
enter_binding = "$modkey+m"
enter_binding_quick_leave = "$modkey+M m"
bindings = {}

[modes.ignore]
enter_binding = "$modkey+i"
enter_binding_quick_leave = "$modkey+M i"
bindings = {}
