modkey = "mod1"
timeout = 400

active_modes = [
  "normal", # first mode listed is default
  "swap",
  "move",
  "ignore"
]

[modes.normal]
enter_binding = "$modkey+n"
enter_binding_quick_leave = "$modkey+m $modkey+n"
enter_cmd = "echo 'n'"
leave_cmd = "echo '!n'"

[modes.normal.bindings]
"$modkey+x $modkey+h" = "echo xh"
"$modkey+x $modkey+j" = "echo xj"
"$modkey+x $modkey+k" = "echo xk"
"$modkey+x $modkey+l" = "echo xl"
"$modkey+h" = "echo h"
"$modkey+j" = "echo j"
"$modkey+k" = "echo k"
"$modkey+l" = "echo l"
"$modkey+shift+h" = "echo H"
"$modkey+shift+j" = "echo J"
"$modkey+shift+k" = "echo K"
"$modkey+shift+l" = "echo L"

[modes.swap]
enter_binding = "$modkey+s"
enter_binding_quick_leave = "$modkey+m $modkey+s"

[modes.swap.bindings]
"$modkey+j" = "echo j-s"

[modes.move]
enter_binding = "$modkey+shift+m"
enter_binding_quick_leave = "$modkey+m $modkey+m"
bindings = {}

[modes.ignore]
enter_binding = "$modkey+i"
enter_binding_quick_leave = "$modkey+m $modkey+i"
bindings = {}
